import React from "react";
import Head from "next/head";
import Flow from "../components/Flow/Flow";
import Ping from "../components/Ping/Ping";

export default function flow() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ height: 300 }}>
        <Flow />
        <Ping />
      </div>
    </div>
  );
}
